"""first migration

Revision ID: 683113dfb306
Revises: 
Create Date: 2025-09-15 20:28:56.971240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683113dfb306'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('main_dish', sa.String(length=255), nullable=False),
    sa.Column('side_dish', sa.String(length=255), nullable=False),
    sa.Column('salad', sa.String(length=255), nullable=False),
    sa.Column('dessert', sa.String(length=255), nullable=False),
    sa.Column('drink', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_date'), ['date'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_date'))

    op.drop_table('menu')
    # ### end Alembic commands ###
